Lane Following and Line Detection
UBC-Snowbots/IARRC-2017 pull request #15
Opened 2017-07-02 02:13 UTC by raadkhan

Using Sliding Window + PolyFit Method

https://chatbotslife.com/self-driving-cars-advanced-computer-vision-with-opencv-finding-lane-lines-488a411b2c3d
https://chatbotslife.com/robust-lane-finding-using-advanced-computer-vision-techniques-46875bb3c8aa

2017-07-02 23:16 UTC, ValRat commented on src/better_lane_follow/src/LineDetect.cpp
> +LineDetect::LineDetect() : initalLineDetectThreshold(200),
These are simple integers, so I don't see a need for an initialisation list - these are generally used if you're constructing more complicated members of a class. Also, `initalLineDetectThreshold(200)` is misspelt.

2017-07-02 23:16 UTC, ValRat commented on src/better_lane_follow/src/LineDetect.cpp
> +    std::vector<int> baseHistogram = getHistogram(binaryImage);
Where is `getHistogram` defined? Needs to be implemented

2017-07-04 01:11 UTC, garethellis0 commented on src/better_lane_follow/src/LineDetect.cpp
> +LineDetect::LineDetect() : initalLineDetectThreshold(200),
How would you suggest initialising them? I'm not super particular about it, but I feel like this is a decent format that forces all the variable initialisation to be in one place. Certainly I've seen integers initialised in production codebases like this.

2017-07-04 01:12 UTC, garethellis0 commented on src/better_lane_follow/src/LineDetect.cpp
> +    std::vector<int> baseHistogram = getHistogram(binaryImage);
`LineDetect::getHistogram` is defined, but this function should be `LineDetect::getLines`, not just `getLines`

2017-07-04 01:18 UTC, raadkhan commented on src/better_lane_follow/src/LineDetect.cpp
> +    std::vector<int> baseHistogram = getHistogram(binaryImage);
resolved

2017-07-05 01:24 UTC, garethellis0 requested changes
Some general notes:
- I think we probably want to remove the `lane_follow` package, and rename `better_lane_follow` to `lane_following` (or something like that). The joy of git is that we can always get files we delete back (even deletions are just changes that can be reverted later down the line), so don't worry too much about losing stuff.

2017-07-05 01:24 UTC, garethellis0 commented on src/better_lane_follow/CMakeLists.txt
> +project(better_lane_follow)
We should probably change the name to just `lane-following`, seeing as it looks like we're just going to toss our first attempt

2017-07-05 01:24 UTC, garethellis0 commented on src/better_lane_follow/include/LineDetect.h
> + * Publishes to:
I'm OK if we remove these two lines. It's likely that subscription and publish topics will change, and these will not, just causing confusion down the line.

2017-07-05 01:24 UTC, garethellis0 commented on src/better_lane_follow/package.xml
> +  <name>better_lane_follow</name>
if we change the package name as per my comment above, will probably have to change it here as well

2017-07-05 01:24 UTC, garethellis0 commented on src/better_lane_follow/src/LineDetect.cpp
> +LineDetect::LineDetect() : initalLineDetectThreshold(200),
@ValRat ?

2017-07-05 01:24 UTC, garethellis0 commented on src/better_lane_follow/test/my_node_rostest.cpp
> + */
Not sure if we're going to have time for rostests along with the unit tests, so let's just remove this file for now. I think it's just copied over from the `IGVC-2017` repo, so we should be able to easily re-add it if needed.

2017-07-05 01:24 UTC, garethellis0 commented on src/better_lane_follow/test/sample_package_test.test
> +</launch>
If we're getting rid of the rostests for now, we can also get rid of this file.

2017-07-08 16:28 UTC, raadkhan commented on src/better_lane_follow/src/LineDetect.cpp
> +    std::vector<Polynomial2D> polyLines = LineDetect::contructPolyLine(linePoints, degree);
first parameter should actually be ```points```

2017-07-12 03:16 UTC, raadkhan commented on src/better_lane_follow/src/LineDetect.cpp
> +LineDetect::LineDetect() : initalLineDetectThreshold(200),
resolved

2017-07-12 03:16 UTC, raadkhan commented on src/better_lane_follow/include/LineDetect.h
> + * Publishes to:
resolved

2017-07-12 03:17 UTC, raadkhan commented on src/better_lane_follow/test/my_node_rostest.cpp
> + */
resolved

2017-07-12 03:17 UTC, raadkhan commented on src/better_lane_follow/test/sample_package_test.test
> +</launch>
resolved

2017-07-13 19:21 UTC, raadkhan commented on src/better_lane_follow/CMakeLists.txt
> +project(better_lane_follow)
done

2017-07-13 19:21 UTC, raadkhan commented on src/better_lane_follow/package.xml
> +  <name>better_lane_follow</name>
done

2018-05-16 22:18 UTC, closed without merging